version: '3'
networks:
  backend:
services:
  frontend:
    image: node:10
    container_name: frontend
#    volumes:
#      - ./Frontend/frontend/src:./usr/frontend/src
    build:
      context: ./Frontend
      dockerfile: ./Dockerfile
    networks:
      backend:
  backend:
    image: openjdk:8-jdk-alpine
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    networks:
      backend:
