version: '3'
networks:
  tacs:

services:
    backend:
      image: openjdk:8-jdk-alpine
      container_name: backend
      build:
        context: ./Backend
        dockerfile: Dockerfile
      environment:
        DB_HOST: tacs_db
        DB_NAME: tacs_db
        DB_USER: root
        DB_USER_PASSWORD: root
        API_SUPERHERO_URL: https://superheroapi.com/api/4309521039059601/
        CLEARDB_DATABASE_URL: jdbc:mysql://tacs_db:3306/tacs_db?createDatabaseIfNotExist=true
#        CLEARDB_DATABASE_URL: jdbc:mysql://localhost:3306/tacs_db?createDatabaseIfNotExist=true
      depends_on:
        - tacs_db
      restart: unless-stopped
      networks:
        tacs:

    tacs_db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      container_name: tacs_db
      ports:
        - 3306:3306
      restart: always
      environment:
        MYSQL_DATABASE: tacs_db
        MYSQL_USER: tacs
        MYSQL_PASSWORD: tacs
        MYSQL_ROOT_PASSWORD: root
      networks:
        tacs: